name: Keep Render Warm (Render)

on:
  schedule:
    - cron: "*/5 * * * *"      # every 5 minutes (UTC)
  workflow_dispatch:           # allow manual trigger

permissions:
  contents: read

concurrency:
  group: keep-render-warm
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Small random jitter
        run: sleep $((RANDOM % 60))

      - name: Ping MCP relay (root)
        continue-on-error: true
        run: |
          URL="https://synorb-mcp-relay-svc.onrender.com/?t=$(date +%s)"
          echo "GET $URL"
          curl -s -o /dev/null -w "HTTP %{http_code}\n" "$URL" || true

      - name: Ping API client (/health)
        continue-on-error: true
        run: |
          URL="https://apiclient-uim1.onrender.com/health?t=$(date +%s)"
          echo "GET $URL"
          curl -s -o /dev/null -w "HTTP %{http_code}\n" "$URL" || true
